### ISSUE TITLE
Add width option to merge command

### ISSUE THREAD

**Issue by robhudson** [mozilla/puente#50]
When I do a extract/merge it creates a lot of churn in git b/c the line wrapping widths vary from Pontoon to our `merge` command. It'd be great if there were an option to override puente's default of 200 with one that matches Pontoon's value of 78.

**Comment by willkg** [comment]
Sorry--I totally missed this when I commented in the PR. My bad.

When we were talking about width issues a while back, there were two issues we ran into:
1. The wrapping mechanics differed. With Puente's code, line wrapping sometimes puts the space at the beginning of the next line for reasons I don't understand. Pretty sure this was in extract and not merge, but it might have been a problem with both.
2. Django's `makemessages` doesn't have a width argument. If we're really moving towards vanilla Django, then should we have this?

I suspect item 1 means we'll still have problems with Pontoon regardless of the width we choose, but it's likely we can reduce the issues significantly by specifying a width.

I don't know what to do about item 2. Do we know what the widths Django's makemessages choose are? Maybe we can default to that? Maybe we should fix Pontoon?

In the meantime, if it makes life easier, I'm game for landing pr #51 for now, but make it one of the things we figure out in order to get rid of Puente.

**Comment by robhudson** [comment]
I wouldn't land PR #51 -- it neither fixes the problem nor makes it worse. And it's simple to add later if we decide.

I agree with the goals of going vanilla Django. I would also like to make less churn in the diffs if possible. We can keep this open maybe in hopes to do that. I don't know if it's all projects that experience this or not.

**Comment by willkg** [comment]
If polib does wrapping right, then writing a utility that reads in a `.po` file and then writes it back out using polib is pretty easy. We can see if that helps at all.

I forget if our problem is with the output of msgmerge or the output of the extract command (which uses Babel to extract). Depending on that, we might be able to send a patch upstream to fix weird wrapping. If doing a patch upstream is too hard, we could write a rewrap command that opens the file with polib and writes it back out with a specified wrap length. That should be easy to write. Maybe msgcat can do that, too?

**Comment by willkg** [comment]
What's Pontoon's wrapping width? We could just change it to use that for now to reduce the churn.

**Comment by willkg** [comment]
Per #74, we're ending Puente. Closing this out.
