### ISSUE TITLE
locale/compendia is unused by merge

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/puente#66]
The merge command say that the ``locale/compendia`` directory will be used by ``./manage.py merge``:

https://github.com/mozilla/puente/blob/7c04aadc22b8d9dbb5c556329019909e1180f85a/puente/management/commands/merge.py#L21-L26

During some recent tests (https://github.com/mozilla/kuma/pull/5302), compendia in this folder were not used to initialize a new ``.po`` file from the template ``.pot`` file. I suspect this functionality was removed, but the docstring wasn't cleaned up. I was able to write commands to get the desired behavior.

**Comment by willkg** [comment]
Ok, so this is interesting. This is "my code", but that's not my writing style. Looks like I lifted it from Tower:

https://github.com/clouserw/tower/blob/e2ac254f7dac887952441592f7772af7bb25cc7b/tower/management/commands/merge.py#L26

I bet I never re-implemented the compendia stuff. It's probably because I wasn't using that feature and/or didn't understand it and/or it had no tests so I didn't know how to verify it.

Sorry about that! :cry:
