### ISSUE TITLE
Support jinja2 3.10+

### ISSUE THREAD

**Issue by eviljeff** [mozilla/puente#73]
jinja 3.10 removed some deprecated features https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0
Looks like from [test fails](https://app.circleci.com/pipelines/github/mozilla/addons-server/21676/workflows/993a2688-a2ae-4b43-ae5e-3e3c155b9fce/jobs/117657) "contextfilter and contextfunction are replaced by pass_context." is the problematic change, but there may be others.

**Comment by willkg** [comment]
I was just looking through all the projects I'm the maintainer on and figuring out which ones to prune because I'm overwhelmed. This is at the top of the list because I figured we (collectively) must be beyond the point where this project is needed by now.

If you want to take it over, that'd be great! If not, can you find someone else who's using it to take it over? If not, I'm going to archive it.

**Comment by willkg** [comment]
Per #74, we're ending Puente. Closing this out.
